# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(default='', help_text='Press "Tab" to refresh the map', max_length=80)),
                ('address2', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(default='', max_length=80)),
                ('province', models.CharField(default='AB', max_length=80)),
                ('postalcode', models.CharField(blank=True, max_length=80, null=True)),
                ('longitude', models.FloatField(default=-112, help_text='WGS84 Decimal Degree. Press "Tab" to refresh the map')),
                ('latitude', models.FloatField(default=52, help_text='WGS84 Decimal Degree. Press "Tab" to refresh the map')),
                ('mpoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
